### ISSUE TITLE
Wishlist/purchase tracker

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mtg-collection-tracker#8]
Ability to:

 * [x] Enter/update/delete card/qty
    * [x] Convert to SKUs in collection when purchased
 * [x] Register storefronts for price comparison
 * [x] Enter/update storefront qty/pricing for given card
 * [x] Price compare against various storefronts
 * [x] Generate optimised buying list based on storefront price comparison
 * [x] Show total required spend on bottom right corner
 * [x] BUG: If qty/edition is edited, that values are lost when item is moved to collection
